addSbtPlugin("com.eed3si9n"      % "sbt-assembly" % "0.15.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.0")
addSbtPlugin("io.spray"          % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"  % "0.5.1")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"   % "2.8.5")
