POST localhost:9000/orders
Content-Type: application/json

{
  "customerId": "8d07abfc-c3cf-4651-a77d-f6037377f06b",
  "itemId": "item1",
  "quantity": 1
}

###
POST localhost:9000/orders
Content-Type: application/json

{
  "customerId": "8d07abfc-c3cf-4651-a77d-f6037377f06b",
  "itemId": "item-not-found",
  "quantity": 3
}

###
GET localhost:9000/orders/84256d35-1751-4884-a1cf-dd7e4561962f
